#ifndef ERRORCODES_H
#define ERRORCODES_H

#define CANNOT_CREATE_CRYPTICIZER_DIRECTORY 2
#define PASSWORD_DO_NOT_MATCH 3
#define CANNOT_GENERATE_SALT 4
#define CANNOT_INITIALIZE_DIGEST 5
#define CANNOT_UPDATE_DIGEST 6
#define CANNOT_FINALIZE_DIGEST 7

#endif
